connect 'jdbc:derby://localhost:1527/BaseDeGens;create=true';

CREATE TABLE Person
(
    id integer primary key GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    firstName varchar( 255 ) not null,
    lastName varchar( 255 ) not null
);

CREATE TABLE Relations
(
    personID integer not null REFERENCES Person( id ),
    otherPersonID integer not null REFERENCES Person( id ),
    label varchar( 255 ) not null,
    PRIMARY KEY ( personID, otherPersonID )
);
